dist: trusty
sudo: false
git:
  # use depth 2 just in case two refs get pushed at once (like a tag)
  depth: 2
language: ruby
rvm:
- 2.5.1
script: bundle exec rake spec
deploy:
  provider: rubygems
  api_key: ${RUBYGEMS_API_KEY}
  gem: kramdown-asciidoc
  on:
    tags: true
    repo: opendevise/kramdown-asciidoc
    rvm: *release_rvm
