dist: trusty
git:
  # use depth 2 just in case two refs get pushed at once (like a tag)
  depth: 2
language: ruby
rvm:
- 2.4.5
- 2.3.8
- jruby-9.2.5.0
matrix:
  include:
  - rvm: &release_rvm 2.5.1
    env: COVERAGE=deep
install: bundle install --jobs=3 --retry=3 --without=docs
script: bundle exec rake spec
deploy:
  provider: rubygems
  api_key: ${RUBYGEMS_API_KEY}
  gem: kramdown-asciidoc
  on:
    tags: true
    repo: asciidoctor/kramdown-asciidoc
    rvm: *release_rvm
